# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import qiniu_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('img_url', qiniu_fields.fields.QiniuFileField(max_length=500, verbose_name='图片')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': 'Banner',
                'verbose_name': 'Banner',
            },
        ),
    ]
